services:
  postgres:
    image: postgres:16
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/data

volumes:
  postgres_data: